# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build dockerBuildImage'
- task: CopyFiles@2
  inputs:
    sourceFolder: 'build/distributions'
    contents: '**/*'
    targetFolder: $(Build.ArtifactStagingDirectory)/distributions
- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'distributions'
    pathtoPublish: $(Build.ArtifactStagingDirectory)/distributions
- script: docker images